[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "flower_DP"
version = "1.0.0"
description = "Central Differential Privacy and Secure Aggregation in Flower"
license = "Apache-2.0"
dependencies = [
    "flwr[simulation]>=1.15.2",
    "flwr-datasets[vision]>=0.5.0",
    "torch==2.5.1",
    "torchvision==0.20.1",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.flwr.app]
publisher = "flwrlabs"

[tool.flwr.app.components]
serverapp = "flower_DP.server:app"
clientapp = "flower_DP.client:app"

[tool.flwr.app.config]
# Parameters for the DP
noise-multiplier = 0.2
clipping-norm = 10
num-sampled-clients = 20
# Parameters for the SecAgg+ protocol
num-shares = 7
reconstruction-threshold = 4

[tool.flwr.federations]
default = "local-simulation-gpu"

[tool.flwr.federations.local-simulation-gpu]
options.num-supernodes = 100